package com.andforce.andclaw.plan

import android.content.Context
import com.andforce.andclaw.model.AiAction
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import org.json.JSONArray
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID

class PlanManager(context: Context) {
    private val appContext = context.applicationContext
    private val gson: Gson = GsonBuilder().setPrettyPrinting().create()
    private val rootDir = File(appContext.filesDir, "agent_plans")

    fun createPlan(goal: String): AgentPlan {
        return createPlan(goal, null)
    }

    fun createPlan(goal: String, draft: PlanDraft?): AgentPlan {
        rootDir.mkdirs()
        val now = System.currentTimeMillis()
        val id = buildPlanId(now, goal)
        val draftedSteps = draft?.steps
            ?.mapIndexedNotNull { index, step -> step.toPlanStep(index) }
            ?.takeIf { it.isNotEmpty() }
        val plan = AgentPlan(
            id = id,
            goal = goal,
            status = PlanStatus.RUNNING,
            createdAt = now,
            updatedAt = now,
            summary = draft?.summary?.takeIf { it.isNotBlank() }?.take(120) ?: goal.take(120),
            currentStepId = draftedSteps?.firstOrNull()?.id ?: "step-1",
            steps = draftedSteps ?: listOf(
                PlanStep(
                    id = "step-1",
                    title = "Observe current device state",
                    description = "Capture the current UI state and identify the safest next route.",
                    status = StepStatus.IN_PROGRESS,
                    type = StepType.OBSERVE
                ),
                PlanStep(
                    id = "step-2",
                    title = "Execute toward the goal",
                    description = "Use Android actions step by step, updating the plan as new UI state appears.",
                    type = StepType.UI_ACTION
                ),
                PlanStep(
                    id = "step-3",
                    title = "Verify completion",
                    description = "Check that the user's requested outcome is actually complete before finishing.",
                    type = StepType.VERIFY
                )
            )
        )
        save(plan)
        return plan
    }

    fun listPlans(): List<PlanListItem> {
        if (!rootDir.exists()) return emptyList()
        return rootDir.listFiles()
            ?.mapNotNull { dir -> loadPlan(dir.name) }
            ?.sortedByDescending { it.updatedAt }
            ?.map { plan ->
                PlanListItem(
                    id = plan.id,
                    goal = plan.goal,
                    summary = plan.summary,
                    status = plan.status,
                    updatedAt = plan.updatedAt,
                    currentStepId = plan.currentStepId
                )
            }
            ?: emptyList()
    }

    fun loadLatestUnfinishedPlan(): AgentPlan? =
        listPlans()
            .firstOrNull { it.status in setOf(PlanStatus.RUNNING, PlanStatus.PLANNING, PlanStatus.PAUSED, PlanStatus.BLOCKED) }
            ?.let { loadPlan(it.id) }

    fun loadPlan(planId: String): AgentPlan? {
        val file = File(File(rootDir, planId), "plan.json")
        if (!file.exists()) return null
        return runCatching { gson.fromJson(file.readText(), AgentPlan::class.java) }.getOrNull()
    }

    fun readPlanMarkdown(planId: String): String? {
        val file = File(File(rootDir, planId), "plan.md")
        return if (file.exists()) runCatching { file.readText() }.getOrNull() else null
    }

    fun parseDraft(rawResponse: String): PlanDraft? =
        runCatching { gson.fromJson(extractJsonObject(rawResponse), PlanDraft::class.java) }.getOrNull()

    fun parsePatch(rawResponse: String): PlanPatch? =
        runCatching { gson.fromJson(extractJsonObject(rawResponse), PlanPatch::class.java) }.getOrNull()

    fun parseVerification(rawResponse: String): StepVerification? =
        runCatching { gson.fromJson(extractJsonObject(rawResponse), StepVerification::class.java) }.getOrNull()

    fun replaceWithDraft(plan: AgentPlan?, draft: PlanDraft?): AgentPlan? {
        if (plan == null || draft == null || draft.steps.isEmpty()) return plan
        val draftedSteps = draft.steps.mapIndexedNotNull { index, step -> step.toPlanStep(index) }
        if (draftedSteps.isEmpty()) return plan
        return plan.copy(
            status = PlanStatus.RUNNING,
            updatedAt = System.currentTimeMillis(),
            summary = draft.summary?.takeIf { it.isNotBlank() }?.take(120) ?: plan.summary,
            steps = draftedSteps,
            currentStepId = draftedSteps.first().id,
            memory = plan.memory.copy(
                decisions = appendLimited(plan.memory.decisions, "Initial long-term plan generated by planner")
            )
        ).also(::save)
    }

    fun applyPatch(plan: AgentPlan?, patch: PlanPatch?): AgentPlan? {
        if (plan == null || patch == null) return plan
        var currentStepId = plan.currentStepId
        var steps = plan.steps
        patch.updates.forEach { update ->
            update.currentStepId?.takeIf { id -> steps.any { it.id == id } }?.let { currentStepId = it }
            if (update.step != null && update.insertAfter != null) {
                val newStep = update.step.toPlanStep(steps.size)
                if (newStep != null && steps.none { it.id == newStep.id }) {
                    val insertIndex = steps.indexOfFirst { it.id == update.insertAfter }
                    steps = if (insertIndex >= 0) {
                        steps.toMutableList().apply { add(insertIndex + 1, newStep) }
                    } else {
                        steps + newStep
                    }
                }
            }
            update.stepId?.let { stepId ->
                steps = steps.map { step ->
                    if (step.id != stepId) {
                        step
                    } else {
                        step.copy(
                            status = update.status?.toStepStatus() ?: step.status,
                            evidence = update.evidence?.let { appendLimited(step.evidence, it) } ?: step.evidence,
                            lastError = update.lastError ?: step.lastError
                        )
                    }
                }
            }
        }
        if (currentStepId == null || steps.none { it.id == currentStepId }) {
            currentStepId = steps.firstOrNull { it.status == StepStatus.IN_PROGRESS || it.status == StepStatus.TODO }?.id
        }
        return plan.copy(
            status = PlanStatus.RUNNING,
            updatedAt = System.currentTimeMillis(),
            steps = steps,
            currentStepId = currentStepId,
            memory = plan.memory.copy(
                decisions = appendLimited(plan.memory.decisions, "Plan patched: ${patch.reason.orEmpty()}".trim()),
                blockers = patch.reason?.takeIf { it.isNotBlank() }?.let { appendLimited(plan.memory.blockers, it) }
                    ?: plan.memory.blockers
            )
        ).also(::save)
    }

    fun recordAction(plan: AgentPlan?, action: AiAction): AgentPlan? {
        if (plan == null) return null
        val stepId = action.currentStepId ?: plan.currentStepId ?: nextRunnableStep(plan)?.id
        val now = System.currentTimeMillis()
        val updatedSteps = plan.steps.map { step ->
            if (step.id != stepId) {
                step
            } else {
                step.copy(
                    status = StepStatus.IN_PROGRESS,
                    attempts = step.attempts + 1,
                    evidence = appendLimited(
                        step.evidence,
                        "Action: ${action.type}; progress=${action.progress.orEmpty()}; reason=${action.reason.orEmpty()}"
                    )
                )
            }
        }
        return plan.copy(
            status = PlanStatus.RUNNING,
            updatedAt = now,
            currentStepId = stepId,
            steps = updatedSteps,
            memory = plan.memory.copy(
                decisions = appendLimited(
                    plan.memory.decisions,
                    "Selected action ${action.type} for ${stepId ?: "unknown step"}"
                )
            )
        ).also(::save)
    }

    fun recordObservation(plan: AgentPlan?, message: String): AgentPlan? {
        if (plan == null || message.isBlank()) return plan
        return plan.copy(
            updatedAt = System.currentTimeMillis(),
            memory = plan.memory.copy(observations = appendLimited(plan.memory.observations, message))
        ).also(::save)
    }

    fun applyVerification(plan: AgentPlan?, verification: StepVerification?): AgentPlan? {
        if (plan == null || verification == null) return plan
        if (verification.taskComplete) {
            return markDone(plan, verification.evidence ?: "Verifier marked task complete")
        }
        val blocker = verification.blocker?.takeIf { it.isNotBlank() }
        val updatedPlan = PlanProgression.applyVerification(
            plan = plan,
            verification = verification,
            appendLimited = ::appendLimited
        )
        return updatedPlan.copy(
            status = if (blocker != null) PlanStatus.BLOCKED else PlanStatus.RUNNING,
            updatedAt = System.currentTimeMillis(),
            memory = plan.memory.copy(
                observations = verification.evidence?.takeIf { it.isNotBlank() }?.let {
                    appendLimited(plan.memory.observations, "Verifier: $it")
                } ?: plan.memory.observations,
                blockers = blocker?.let { appendLimited(plan.memory.blockers, it) } ?: plan.memory.blockers
            )
        ).also(::save)
    }

    fun recordFailure(plan: AgentPlan?, message: String, terminal: Boolean = false): AgentPlan? {
        if (plan == null) return null
        val stepId = plan.currentStepId
        val updatedSteps = plan.steps.map { step ->
            if (step.id == stepId) {
                step.copy(
                    status = if (terminal) StepStatus.FAILED else StepStatus.BLOCKED,
                    lastError = message
                )
            } else {
                step
            }
        }
        return plan.copy(
            status = if (terminal) PlanStatus.FAILED else PlanStatus.BLOCKED,
            updatedAt = System.currentTimeMillis(),
            steps = updatedSteps,
            memory = plan.memory.copy(blockers = appendLimited(plan.memory.blockers, message))
        ).also(::save)
    }

    fun markDone(plan: AgentPlan?, reason: String?): AgentPlan? {
        if (plan == null) return null
        val now = System.currentTimeMillis()
        val updatedSteps = plan.steps.map { step ->
            if (step.status == StepStatus.DONE || step.status == StepStatus.SKIPPED) {
                step
            } else {
                step.copy(
                    status = StepStatus.DONE,
                    evidence = appendLimited(step.evidence, reason ?: "Task completed")
                )
            }
        }
        return plan.copy(
            status = PlanStatus.DONE,
            updatedAt = now,
            steps = updatedSteps,
            currentStepId = null
        ).also(::save)
    }

    fun markCancelled(plan: AgentPlan?, reason: String?): AgentPlan? {
        if (plan == null || plan.status == PlanStatus.DONE || plan.status == PlanStatus.FAILED) return plan
        return plan.copy(
            status = PlanStatus.CANCELLED,
            updatedAt = System.currentTimeMillis(),
            memory = plan.memory.copy(blockers = appendLimited(plan.memory.blockers, reason ?: "Agent stopped"))
        ).also(::save)
    }

    fun toPromptContext(plan: AgentPlan?): String? {
        if (plan == null) return null
        val current = plan.steps.firstOrNull { it.id == plan.currentStepId }
        val stepLines = plan.steps.joinToString("\n") { step ->
            val details = mutableListOf(
                "- ${step.id} [${step.status}]: ${step.title} (${step.type})",
                "  description: ${step.description}"
            )
            step.evidence.takeLast(3).forEach { evidence ->
                details += "  evidence: $evidence"
            }
            step.lastError?.takeIf { it.isNotBlank() }?.let { lastError ->
                details += "  last_error: $lastError"
            }
            details.joinToString("\n")
        }
        val observations = plan.memory.observations.takeLast(5).joinToString("\n") { "- $it" }.ifBlank { "- None" }
        val decisions = plan.memory.decisions.takeLast(5).joinToString("\n") { "- $it" }.ifBlank { "- None" }
        val blockers = plan.memory.blockers.takeLast(5).joinToString("\n") { "- $it" }.ifBlank { "- None" }
        return """
Long-term plan id: ${plan.id}
Plan status: ${plan.status}
Goal: ${plan.goal}
Current step: ${current?.id ?: "none"} - ${current?.title ?: "none"}
Steps:
$stepLines

Recent observations:
$observations

Recent decisions:
$decisions

Recent blockers:
$blockers

Use current_step_id in your JSON response. If the current step is complete, continue with the next unfinished step.
Preserve the user's original goal wording exactly. Do not add new semantic requirements while verifying or executing later steps.
If the plan no longer fits the observed screen, explain the blocker in reason and choose a safer next action.
		""".trimIndent()
    }

    fun toVerifierPromptContext(plan: AgentPlan?): String? {
        if (plan == null) return null
        val currentIndex = plan.steps.indexOfFirst { it.id == plan.currentStepId }.coerceAtLeast(0)
        val relevantSteps = plan.steps
            .mapIndexedNotNull { index, step ->
                val isRelevant = index == currentIndex ||
                    index == currentIndex + 1 ||
                    step.status == StepStatus.BLOCKED ||
                    step.status == StepStatus.FAILED
                if (isRelevant) step else null
            }
            .distinctBy { it.id }

        val stepLines = relevantSteps.joinToString("\n") { step ->
            val details = mutableListOf(
                "- ${step.id} [${step.status}]: ${step.title} (${step.type})",
                "  done_when: ${step.description}"
            )
            step.evidence.takeLast(1).forEach { evidence ->
                details += "  evidence: $evidence"
            }
            step.lastError?.takeIf { it.isNotBlank() }?.let { lastError ->
                details += "  last_error: $lastError"
            }
            details.joinToString("\n")
        }.ifBlank { "- None" }

        val observations = plan.memory.observations.takeLast(2).joinToString("\n") { "- $it" }.ifBlank { "- None" }
        val blockers = plan.memory.blockers.takeLast(2).joinToString("\n") { "- $it" }.ifBlank { "- None" }
        return """
Goal: ${plan.goal}
Plan status: ${plan.status}
Current step: ${plan.currentStepId ?: "none"}
Relevant steps:
$stepLines

Recent observations:
$observations

Recent blockers:
$blockers

Verifier scope: decide only whether the current step is done, blocked, or still in progress. If it is done, choose the next unfinished relevant step.
		""".trimIndent()
    }

    fun formatProgress(plan: AgentPlan?, title: String? = null): String? {
        if (plan == null) return null
        val done = plan.steps.count { it.status == StepStatus.DONE || it.status == StepStatus.SKIPPED }
        val total = plan.steps.size.coerceAtLeast(1)
        val percent = done * 100 / total
        val current = plan.steps.firstOrNull { it.id == plan.currentStepId }
        val stepLines = plan.steps.joinToString("\n") { step ->
            val marker = when (step.status) {
                StepStatus.DONE -> "[x]"
                StepStatus.IN_PROGRESS -> "[>]"
                StepStatus.BLOCKED -> "[!]"
                StepStatus.FAILED -> "[failed]"
                StepStatus.SKIPPED -> "[-]"
                StepStatus.TODO -> "[ ]"
            }
            "$marker ${step.id}: ${step.title}"
        }
        val heading = title?.takeIf { it.isNotBlank() } ?: "Plan progress"
        return """
$heading
Status: ${plan.status}
Progress: $done/$total ($percent%)
Current: ${current?.id ?: "none"} - ${current?.title ?: "none"}

$stepLines
""".trimIndent()
    }

    fun planDir(plan: AgentPlan): File = File(rootDir, plan.id)

    private fun save(plan: AgentPlan) {
        val dir = planDir(plan)
        dir.mkdirs()
        File(dir, "plan.json").writeText(gson.toJson(plan))
        File(dir, "plan.md").writeText(renderMarkdown(plan))
    }

    private fun renderMarkdown(plan: AgentPlan): String {
        val updated = formatTime(plan.updatedAt)
        val created = formatTime(plan.createdAt)
        val steps = plan.steps.joinToString("\n\n") { step ->
            val box = when (step.status) {
                StepStatus.DONE -> "x"
                else -> " "
            }
            val evidence = if (step.evidence.isEmpty()) {
                ""
            } else {
                "\n  Evidence:\n" + step.evidence.takeLast(5).joinToString("\n") { "  - $it" }
            }
            val error = step.lastError?.let { "\n  Last error: $it" }.orEmpty()
            "- [$box] ${step.id}: ${step.title}\n  Status: ${step.status}\n  Type: ${step.type}\n  Attempts: ${step.attempts}\n  Description: ${step.description}$evidence$error"
        }
        val observations = plan.memory.observations.takeLast(10).joinToString("\n") { "- $it" }.ifBlank { "- None" }
        val decisions = plan.memory.decisions.takeLast(10).joinToString("\n") { "- $it" }.ifBlank { "- None" }
        val blockers = plan.memory.blockers.takeLast(10).joinToString("\n") { "- $it" }.ifBlank { "- None" }

        return """
# Plan: ${plan.summary}

Status: ${plan.status}
Current Step: ${plan.currentStepId ?: "none"}
Created: $created
Updated: $updated

## Goal
${plan.goal}

## Steps

$steps

## Observations
$observations

## Decisions
$decisions

## Blockers
$blockers
""".trimIndent() + "\n"
    }

    private fun nextRunnableStep(plan: AgentPlan): PlanStep? =
        plan.steps.firstOrNull { it.status == StepStatus.IN_PROGRESS }
            ?: plan.steps.firstOrNull { it.status == StepStatus.TODO }

    private fun appendLimited(items: List<String>, item: String, max: Int = 40): List<String> =
        (items + item.take(500)).takeLast(max)

    private fun PlanDraftStep.toPlanStep(index: Int): PlanStep? {
        val safeTitle = title?.takeIf { it.isNotBlank() } ?: return null
        val safeId = id?.takeIf { it.isNotBlank() } ?: "step-${index + 1}"
        return PlanStep(
            id = safeId,
            title = safeTitle.take(80),
            description = description?.takeIf { it.isNotBlank() }?.take(500) ?: safeTitle,
            status = if (index == 0) StepStatus.IN_PROGRESS else StepStatus.TODO,
            type = type.toStepType()
        )
    }

    private fun String?.toStepType(): StepType = when (this?.uppercase(Locale.US)) {
        "OBSERVE" -> StepType.OBSERVE
        "API_ACTION" -> StepType.API_ACTION
        "VERIFY" -> StepType.VERIFY
        "DECISION" -> StepType.DECISION
        else -> StepType.UI_ACTION
    }

    private fun String.toStepStatus(): StepStatus? = when (uppercase(Locale.US)) {
        "TODO" -> StepStatus.TODO
        "IN_PROGRESS" -> StepStatus.IN_PROGRESS
        "DONE" -> StepStatus.DONE
        "BLOCKED" -> StepStatus.BLOCKED
        "FAILED" -> StepStatus.FAILED
        "SKIPPED" -> StepStatus.SKIPPED
        else -> null
    }

    private fun extractJsonObject(rawResponse: String): String {
        val fenced = Regex("(?s)```(?:json)?\\s*(.*?)\\s*```").find(rawResponse)
            ?.groups
            ?.get(1)
            ?.value
            ?.trim()
        val content = fenced ?: rawResponse.trim()
        if (content.startsWith("[{")) {
            return JSONArray(content).getJSONObject(0).toString()
        }
        val start = content.indexOf('{')
        val end = content.lastIndexOf('}')
        require(start >= 0 && end > start) { "No JSON object found" }
        return content.substring(start, end + 1)
    }

    private fun buildPlanId(now: Long, goal: String): String {
        val time = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.US).format(Date(now))
        val slug = goal.lowercase(Locale.US)
            .replace(Regex("[^a-z0-9\\u4e00-\\u9fa5]+"), "-")
            .trim('-')
            .take(32)
            .ifBlank { UUID.randomUUID().toString().take(8) }
        return "${time}_$slug"
    }

    private fun formatTime(time: Long): String =
        SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date(time))
}

internal object PlanProgression {
    fun applyVerification(
        plan: AgentPlan,
        verification: StepVerification,
        appendLimited: (List<String>, String) -> List<String>
    ): AgentPlan {
        val currentIndex = plan.steps.indexOfFirst { it.id == plan.currentStepId }.coerceAtLeast(0)
        val rawVerifiedStepId = verification.currentStepId
            ?.takeIf { id -> plan.steps.any { it.id == id } }
            ?: plan.currentStepId
        val rawVerifiedIndex = plan.steps.indexOfFirst { it.id == rawVerifiedStepId }
        val verifierStatus = verification.currentStepStatus.toStepStatusOrNull()

        val verifiedStepId = when {
            rawVerifiedIndex < 0 -> plan.currentStepId
            rawVerifiedIndex < currentIndex && verifierStatus !in setOf(StepStatus.DONE, StepStatus.SKIPPED) -> plan.currentStepId
            else -> rawVerifiedStepId
        }
        val verifiedIndex = plan.steps.indexOfFirst { it.id == verifiedStepId }.takeIf { it >= 0 } ?: currentIndex

        var steps = plan.steps.mapIndexed { index, step ->
            when {
                step.id == verifiedStepId -> step.copy(
                    status = mergeStatus(step.status, verifierStatus),
                    evidence = verification.evidence?.let { appendLimited(step.evidence, it) } ?: step.evidence,
                    lastError = verification.blocker ?: step.lastError
                )
                index < currentIndex && step.status == StepStatus.IN_PROGRESS -> step.copy(
                    status = StepStatus.DONE,
                    evidence = appendLimited(step.evidence, "Advanced past this step.")
                )
                else -> step
            }
        }

        val nextStepFloorIndex = maxOf(currentIndex, verifiedIndex)
        val nextStepId = verification.nextStepId
            ?.takeIf { id -> plan.steps.indexOfFirst { it.id == id } >= nextStepFloorIndex }
            ?.takeIf { id -> plan.steps.any { it.id == id } }
        val currentStepId = when {
            nextStepId != null -> nextStepId
            verifierStatus == StepStatus.DONE -> steps
                .drop(verifiedIndex + 1)
                .firstOrNull { it.status == StepStatus.IN_PROGRESS || it.status == StepStatus.TODO }
                ?.id
            else -> verifiedStepId
        }

        val newCurrentIndex = steps.indexOfFirst { it.id == currentStepId }
        steps = steps.mapIndexed { index, step ->
            when {
                index == newCurrentIndex && step.status == StepStatus.TODO -> step.copy(status = StepStatus.IN_PROGRESS)
                newCurrentIndex >= 0 && index < newCurrentIndex && step.status == StepStatus.IN_PROGRESS -> step.copy(
                    status = StepStatus.DONE,
                    evidence = appendLimited(step.evidence, "Advanced past this step.")
                )
                else -> step
            }
        }

        return plan.copy(steps = steps, currentStepId = currentStepId)
    }

    private fun mergeStatus(existing: StepStatus, incoming: StepStatus?): StepStatus {
        if (incoming == null) return existing
        if (existing in setOf(StepStatus.DONE, StepStatus.SKIPPED) && incoming !in setOf(StepStatus.DONE, StepStatus.SKIPPED)) {
            return existing
        }
        return incoming
    }

    private fun String?.toStepStatusOrNull(): StepStatus? = when (this?.uppercase(Locale.US)) {
        "TODO" -> StepStatus.TODO
        "IN_PROGRESS" -> StepStatus.IN_PROGRESS
        "DONE" -> StepStatus.DONE
        "BLOCKED" -> StepStatus.BLOCKED
        "FAILED" -> StepStatus.FAILED
        "SKIPPED" -> StepStatus.SKIPPED
        else -> null
    }
}
